import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { aeonik, britti, inter } from '@/assets/fonts';
import { Analytics } from '@vercel/analytics/react';
import { ClientProviders } from '@/app/client-providers';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Propal.io',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${aeonik.variable} ${britti.variable}`}
    >
      <body className="antialiased text-foreground">
        <ClientProviders>{children}</ClientProviders>
        <Toaster position="bottom-center" />
        <Analytics />
      </body>
    </html>
  );
}
